#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarciWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db4526dcc7cc9a4725a006a15100314384")]
	public partial class DarciWebDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DarciWebDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db4526dcc7cc9a4725a006a15100314384ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DarciWebDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DarciWebDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DarciWebDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DarciWebDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GalleryItem> GalleryItems
		{
			get
			{
				return this.GetTable<GalleryItem>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GalleryItem")]
	public partial class GalleryItem
	{
		
		private int _GalleryItemId;
		
		private string _ItemText;
		
		private int _SortOrder;
		
		private bool _IsActive;
		
		public GalleryItem()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryItemId", DbType="Int NOT NULL")]
		public int GalleryItemId
		{
			get
			{
				return this._GalleryItemId;
			}
			set
			{
				if ((this._GalleryItemId != value))
				{
					this._GalleryItemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemText", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ItemText
		{
			get
			{
				return this._ItemText;
			}
			set
			{
				if ((this._ItemText != value))
				{
					this._ItemText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int NOT NULL")]
		public int SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this._SortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
